### ISSUE TITLE
[TECH] 수집 정보 수정

### ISSUE THREAD

**Issue by jayden-lee** [weggdul/timeline#21]
@weduls 
[TECH] 컨텐츠 정보 수집 변경사항
- 대표 이미지 (포스팅에서 첫 번째로 사용된 이미지, 만약 없을 경우 로고 사용)
- 컨텐츠 (이미지 태그를 제외한 텍스트 내용만 수집)

**Comment by weduls** [comment]
이슈가 나는 경우가 많은데 수집쪽 다시한번 재검토 바랍니다.

**Comment by jayden-lee** [comment]
@weduls 수집 쪽은 다른 이슈 생성해서 작업할게요
