### ISSUE TITLE
[API] 서버에서 데이터를 캐시 형태로 저장 및 스케줄링

### ISSUE THREAD

**Issue by jayden-lee** [weggdul/timeline#28]
- API 서버에서 Timeline Item 데이터 목록을 캐싱 (키 값은 날짜)
- 주기적으로 스케줄링 하면서 현재 날짜로 데이터 목록 캐싱 갱신
- 배치 작업이 완료되면 배치 성공한 날짜를 저장하는 테이블 새로 생성
- API에서 내려주는 데이터 목록은 publish_dt 기준으로 Desc 정렬

**Comment by jayden-lee** [comment]
@weduls

**Comment by wedul-chul** [comment]
저거 아닌데요..

**Comment by jayden-lee** [comment]
@weduls 
1. 테이블을 만든다 (last_crawle_date: 15215125 - 크롤링된 날짜의 미드나이트 00:00:00의 unixtimestamp)
2. api에서 스케쥴링을 통해 1분에 한번씩 해당 테이블을 찌르고 static 변수에 값을 담고 있는다.
3. api에서 데이터 조회시 update_at조건에 들고있는 static 날짜를 이용해서 조회. 예를 들어 select * from timelin_item ti where 232132 < update_at

**Comment by wedul-chul** [comment]
@jayden-lee 

네 마지막 크롤링 성공시간을 그날짜의 00:00:00의 unix timestamp를 가지고 ㅣㅇㅆ고 데이터 쿼리는 무조건 조건에 마지막 크롤링 날짜보다 큰 update_at을 가진 날짜의 데이터들만 출력되게 해주세용

그럼 내일꺼가 정상적으로 되지 않아도 문제가 없을거고 만약 내일께 정상적으로 수행되면 내일꺼만 화면에 보여질수 있을거같아요

**Comment by jayden-lee** [comment]
@weduls 스케줄링은 30분마다 Batch 마지막 성공한 시간 가져오도록 했습니다.
