### ISSUE TITLE
[JOB] 우아한 형제들 나쁜 api 수정

### ISSUE THREAD

**Issue by weduls** [weggdul/timeline#4]
쿠키 값으로 무엇인가 하게 체크하게 넣어놓고 User-Agent까지 체크하는 나쁜 형제들의 api를 수정하라

**Comment by jayden-lee** [comment]
@weduls 나쁘다고 생각하지마세요. 바뀐 이유가 있겠죠 :)
길게 보세요 😄

**Comment by weduls** [comment]
반영완료하였습니다.
