### ISSUE TITLE
published at 업데이트 로직 변경

### ISSUE THREAD

**Issue by weduls** [weggdul/timeline#72]
published at의 경우 기존에 없는 데이터는 현재날짜 기준으로 집어넣는다. 하지만 업데이트할때도 현재날짜로 업데이트를 하기 때문에 계속 신규 컨텐츠인것처럼 상위에 노출되는 문제가 발생한다.

이를 해결하기 위해 처음 긁어온 데이터의 publishedAt이 없으면 현재시간, 있으면 수정하지 않도록 한다. (다시 publishedAt이 수집되면 그걸로 들어오게는 해야함.)

**Comment by jayden-lee** [comment]
@weduls 이미 해결된 이슈라 종료합니다
