### ISSUE TITLE
[News][Front] 뉴스 UI 추가

### ISSUE THREAD

**Issue by jayden-lee** [weggdul/timeline#74]

**Comment by weduls** [comment]
기존유아이 활용하지마시고 새로 만드세요 타입을

**Comment by jayden-lee** [comment]
@weduls UI 참고 이미지

<b>모바일 네이버 뉴스</b>
<img width="707" alt="스크린샷 2020-02-12 오후 6 07 30" src="https://user-images.githubusercontent.com/43853352/74319699-b68e6180-4dc2-11ea-8138-9cd9d8ca703a.png">
